# Generated by Django 2.2 on 2019-05-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCompA', models.CharField(max_length=50, verbose_name='Nome do Aluno')),
                ('emailPersoA', models.CharField(max_length=50, verbose_name='E-mail')),
                ('senhaA', models.CharField(max_length=12, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeDisc', models.CharField(max_length=50, verbose_name='Disciplina')),
                ('CargaH', models.IntegerField(max_length=50, verbose_name='Carga Horária')),
                ('emailPersoP', models.CharField(max_length=50, verbose_name='E-mail')),
                ('NomeCurs', models.CharField(max_length=50, verbose_name='Nome do Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCompP', models.CharField(max_length=50, verbose_name='Nome do professor')),
                ('emailPersoP', models.CharField(max_length=50, verbose_name='E-mail')),
                ('senhaP', models.CharField(max_length=12, verbose_name='Senha')),
                ('DisciLec', models.CharField(max_length=50, verbose_name='Disciplinas Lecionadas')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15, verbose_name='Login')),
                ('senha', models.CharField(max_length=12, verbose_name='Senha')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
            ],
        ),
    ]
